[package]
name = "recursive-parse"
version = "0.1.0"
authors = ["ryan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.1.1"
escape8259 = "0.5.0"
serde = "1.0.115"
serde_json = "1.0.57"